# Generated by Django 5.2.4 on 2025-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consulta",
            name="update_at",
        ),
        migrations.RemoveField(
            model_name="profissional",
            name="update_at",
        ),
        migrations.AddField(
            model_name="consulta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profissional",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
